export const en = {
  title: "Proxy",
  subtitle:
    "Route specific domains to your local server. Set your browser or system HTTP proxy to use the proxy below.",
  running: "Running",
  failed: "Failed",
  starting: "Starting...",
  startProxy: "Start proxy",
  on: "On",
  off: "Off",
  localRouting: "Local routing",
  failedToStart: "Proxy failed to start",
  failedToStartDesc: 'Check if the port is already in use by another process, then click "Start proxy" to retry.',
  portSettings: "Port settings",
  portSettingsDesc: "Port changes take effect on next app restart.",
  forwardProxyPort: "Forward proxy port",
  reverseHttpPort: "Reverse HTTP (optional)",
  reverseHttpsPort: "Reverse HTTPS (optional)",
  saving: "Saving...",
  save: "Save",
  howToUse: "How to use the proxy",
  forwardProxyHowTo: (port: number | string) =>
    `Forward proxy: Set browser/system HTTP/HTTPS proxy to 127.0.0.1:${port}. The proxy decides by Host whether to send to your local target or pass through.`,
  noSystemProxyHowTo: (port: number | string) =>
    `No system proxy: Open http://127.0.0.1:${port} in the browser (no hosts file). Traffic is routed to the first local route.`,
  openSetupPage: "Open Setup Page",
  addRoute: "Add route",
  domainHost: "Domain (host)",
  targetHost: "Target host",
  targetPort: "Target port",
  add: "Add",
  routes: (count: number) => `Routes (${count})`,
  noRoutesYet: "No routes yet. Add a domain and target above.",
} as const;
