export const en = {
  hero_title: "Monitor Your Digital ",
  hero_title_accent: "Empire",
  hero_description:
    "Watchtower provides real-time health monitoring and performance analytics for all your domains and services. Stay ahead of downtime.",
  hero_btn_dashboard: "Go to Dashboard",
  hero_btn_add: "Add New Targets",
  feature_grid_title: "Advanced Capabilities",
  feature_grid_subtitle: "Powerful features at your fingertips.",
  feature_1_title: "Real-time Monitoring",
  feature_1_desc: "Get instant alerts and detailed status probes with sub-millisecond precision.",
  feature_2_title: "Advanced Analytics",
  feature_2_desc: "Analyze historical logs and latency trends over long periods.",
  feature_3_title: "Smart Groups",
  feature_3_desc: "Organize your infrastructure into logical and functional groups.",
  status_title: "Global System Status",
  status_healthy: "All Systems Operational",
  status_issue: "System Issues Detected",
  status_checking: "Checking System Health...",
  status_last_check: "Last checked at",
} as const;
