export const en = {
  home: "Home",
  domains: "Domains",
  monitor: "Monitor",
  proxy: "Proxy",
  apis: "APIs",
  dashboard: "Dashboard",
  regist: "Regist",
  groups: "Groups",
  logs: "Logs",
  settings: "Settings",
  setup: "Setup",
  schema: "Schema",
  server_logs: "Server Logs",
} as const;
