export const en = {
  title: "User Profile",
  subtitle: "Manage your identity and app preferences",
  name: "Name / Nickname",
  nameHint: "When signed in, this name is shown to workspace members.",
  role: "Role / Position",
  avatarTheme: "Avatar Theme",
  language: "Language",
  appTheme: "App Theme",
  lightMode: "Light",
  darkMode: "Dark",
  save: "Save Changes",
  saved: "Profile saved successfully!",
  feedbackCategory: "Category",
  categoryBug: "Bug report",
  categoryFeature: "Feature request",
  categoryQuestion: "Question",
  telemetryTitle: "Anonymous Usage Data",
  telemetryDesc:
    "Opt-in only. Helps us see which features are actually used. Never collects domains, URLs, request/response bodies, headers, mock content, certificates, file paths, or IPs.",
  telemetryToggleOn: "Sharing enabled",
  telemetryToggleOff: "Sharing disabled",
  telemetryInstallId: "Install ID",
  telemetryRegenerate: "Regenerate ID",
  telemetryRegenerated: "Install ID regenerated.",
};
