export const en = {
  title: "API Settings",
  subtitle: "Register or unregister domains as API logging targets. Multiple selections can be processed at once.",
  searchPlaceholder: "Search by URL or Group name...",
  registeredTitle: (count: number) => `Registered Domains (${count})`,
  unregisteredTitle: (count: number) => `Unregistered Domains (${count})`,
  registeredSubtitle: "Targets for proxy traffic logging and schema management.",
  unregisteredSubtitle: "Registered in Domains but not monitored for APIs.",
  selectAll: "Select All",
  deselectAll: "Deselect All",
  noSearchResults: "No search results.",
  noRegisteredDomains: "No registered domains.",
  allDomainsRegistered: "All domains are registered for API logging.",
  unregisterSelected: (count: number) => `Unregister Selected (${count})`,
  registerSelected: (count: number) => `Register Selected (${count})`,
  loading: "Loading...",
  defaultGroup: "Default",
} as const;
