export const en = {
  title: "Mocking",
  subtitle: "Manage mock rules that intercept API responses.",
  mockRules: "Mock Rules",
  name: "Name",
  description: "Description",
  save: "Save",
  cancel: "Cancel",
  addRule: "Add Rule",
  editRule: "Edit Rule",
  method: "Method",
  urlPattern: "URL Pattern",
  status: "Status",
  enabled: "Enabled",
  disabled: "Disabled",
  headers: "Headers",
  host: "Host (Origin)",
  body: "Body",
  deleteRuleConfirm: "Are you sure you want to delete this rule?",
  noRules: "No Rules",
  noRulesDesc: "Add mock rules to intercept API responses.",
  createRuleSuccess: "Mock rule created.",
  updateRuleSuccess: "Mock rule updated.",
  deleteRuleSuccess: "Mock rule deleted.",
  saveAsMockRule: "Save as Mock Rule",
};
