export const ko = {
  title: "모킹 (Mocking)",
  subtitle: "API 응답을 가로채는 모킹 룰을 관리합니다.",
  mockRules: "모킹 룰",
  name: "이름",
  description: "설명",
  save: "저장",
  cancel: "취소",
  addRule: "룰 추가",
  editRule: "룰 수정",
  method: "메서드",
  urlPattern: "URL 패턴",
  status: "상태 코드",
  enabled: "활성화",
  disabled: "비활성화",
  headers: "헤더",
  host: "호스트 (Origin)",
  body: "바디",
  deleteRuleConfirm: "이 모킹 룰을 삭제하시겠습니까?",
  noRules: "룰 없음",
  noRulesDesc: "API 응답을 가로챌 모킹 룰을 추가하세요.",
  createRuleSuccess: "모킹 룰이 생성되었습니다.",
  updateRuleSuccess: "모킹 룰이 수정되었습니다.",
  deleteRuleSuccess: "모킹 룰이 삭제되었습니다.",
  saveAsMockRule: "모킹 룰로 저장",
};
