export const en = {
  title: "API Client",
  subtitle: "Construct and execute manual API requests, analyzing response data and headers in real-time.",
  method: "Method",
  url: "Request URL",
  send: "Send",
  sending: "Sending...",
  headers: "Request Headers",
  customHeaders: "Custom Headers",
  headerKey: "Header",
  headerValue: "Value",
  body: "Request Body",
  response: "Response",
  responseStatus: "Status Code",
  responseTime: "Elapsed Time",
  responseHeaders: "Response Headers",
  responseBody: "Response Body",
  history: "History",
  noHistory: "No request history found.",
  addHeader: "Add Header",
  key: "Key",
  value: "Value",
  raw: "Raw (JSON/Text)",
  validateSchema: "Validate Response via JSON Schema",
  schemaText: "JSON Schema Definition",
  invalidJson: "Invalid JSON format.",
  schemaPassed: "JSON Schema Validation Passed!",
  schemaFailed: "JSON Schema Validation Failed: ",
  clearHistory: "Clear History",
  importToPipeline: "Export to Pipeline",
  queryParams: "Query Params",
  addQueryParam: "Add Query Param",
  paramKey: "Parameter Key",
  paramValue: "Value",
  origin: "Origin",
  pathname: "Path",
  empty: "(Empty Body)",
  btnCopy: "Copy",
  copied: "Copied!",
  copiedDesc: "Copied to clipboard successfully.",
  copyHtml: "Copy HTML",
  copyMarkdown: "Copy Markdown",
};
