export const ko = {
  title: "API 클라이언트",
  subtitle: "API 요청을 직접 작성하여 전송하고, 응답 데이터 및 헤더 정보를 실시간으로 분석합니다.",
  method: "메서드",
  url: "요청 URL",
  send: "전송",
  sending: "전송 중...",
  headers: "요청 헤더",
  customHeaders: "커스텀 헤더",
  headerKey: "헤더",
  headerValue: "값",
  body: "요청 본문",
  response: "응답 결과 (Response)",
  responseStatus: "상태 코드",
  responseTime: "소요 시간",
  responseHeaders: "응답 헤더",
  responseBody: "응답 본문",
  history: "요청 히스토리",
  noHistory: "보낸 요청 내역이 없습니다.",
  addHeader: "헤더 추가",
  key: "헤더명 (Key)",
  value: "값 (Value)",
  raw: "Raw (JSON/Text)",
  validateSchema: "응답 JSON Schema 검증",
  schemaText: "JSON Schema 정의",
  invalidJson: "올바르지 않은 JSON 형식입니다.",
  schemaPassed: "JSON Schema 검증 성공!",
  schemaFailed: "JSON Schema 검증 실패: ",
  clearHistory: "내역 삭제",
  importToPipeline: "파이프라인으로 내보내기",
  queryParams: "쿼리 파라미터 (Query Params)",
  addQueryParam: "파라미터 추가",
  paramKey: "파라미터명 (Key)",
  paramValue: "값 (Value)",
  origin: "Origin",
  pathname: "Path",
  empty: "(본문 없음)",
  btnCopy: "복사",
  copied: "복사 완료!",
  copiedDesc: "클립보드에 복사되었습니다.",
  copyHtml: "HTML 복사",
  copyMarkdown: "Markdown 복사",
};
