export const en = {
  title: "Real-time Monitor",
  lastSynched: "Last synched",
  viewLogs: "View logs",
  refresh: "Refresh",
  copyReport: "Copy Report",
  healthy: "Healthy",
  warnings: "Warnings",
  critical: "Critical",
  latencyAvg: "Latency avg",
  filterPlaceholder: "Filter by domain name...",
  noMatchingChecks: "No matching monitor checks",
  noMatchingDesc: "Try adjusting your filters or search terms.",
  resetFilters: "Reset Filters",
  reportTitle: (time: string) => `🌍 Monitoring Report (${time})`,
  reportCopied: "Report copied to clipboard!",
  noDomainTitle: "No domains registered yet",
  noDomainDesc: "Register a domain to start monitoring its health status.",
  noDomainAction: "Register a Domain",
  noDataTitle: "No monitoring data yet",
  noDataDesc: "Health checks run automatically. Check back in a moment.",
} as const;
