import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Download } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import type { ProxyStatusPayload } from "@/entities/proxy/types/local_route";
import { invokeApi } from "@/shared/api";
import { Button } from "@/shared/ui/button/Button";
import { Card } from "@/shared/ui/card/card";
import { H1, H2, P } from "@/shared/ui/typography/typography";

export const Route = createFileRoute("/proxy/setup")({
  component: ProxySetupPage,
});

function ProxySetupPage() {
  const [proxyStatus, setProxyStatus] = useState<ProxyStatusPayload>({
    running: false,
    port: 0,
    reverse_http_port: null,
    reverse_https_port: null,
    local_routing_enabled: true,
  });
  const [loading, setLoading] = useState(true);

  const fetchData = useCallback(async () => {
    try {
      const statusRes = await invokeApi("get_proxy_status");
      if (statusRes?.success && statusRes.data) {
        setProxyStatus(statusRes.data);
      }
    } catch (e) {
      console.error("proxy setup fetch:", e);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  const port = proxyStatus.running ? proxyStatus.port : 0;
  const pacUrl = port > 0 ? `http://127.0.0.1:${port}/.watchtower/proxy.pac` : "";

  const handleSaveRootCA = async () => {
    try {
      const res = await invokeApi("save_root_ca");
      if (res.success) {
        alert("Root CA certificate saved successfully!");
      }
    } catch (e: any) {
      if (e !== "Save cancelled") {
        console.error("save_root_ca:", e);
        alert("Failed to save Root CA certificate.");
      }
    }
  };

  if (loading) {
    return (
      <div className="flex flex-col gap-6 pb-20">
        <div className="flex items-center gap-2 text-slate-500">
          <span className="animate-pulse">Loading…</span>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-8 pb-20">
      <div className="flex items-center gap-4">
        <Link to="/proxy" className="text-slate-600 hover:text-slate-900">
          <ArrowLeft className="w-5 h-5" />
        </Link>
        <H1>Proxy Setup</H1>
      </div>

      {!proxyStatus.running ? (
        <Card className="p-6">
          <P className="text-slate-600">Proxy is not running. Start the proxy from the Proxy page first.</P>
          <Link to="/proxy">
            <Button variant="primary" className="mt-4">
              Go to Proxy
            </Button>
          </Link>
        </Card>
      ) : (
        <div className="flex flex-col gap-8">
          {/* HTTPS Root CA */}
          <Card className="p-6">
            <H2 className="mb-4">HTTPS Certificate Installation (Root CA)</H2>
            <P className="text-slate-600 mb-6">
              To enable HTTPS interception for all domains, you must install the <strong>Watchtower Root CA</strong>{" "}
              once. This allows your browser to trust the secure connections generated by Watchtower.
            </P>

            <div className="flex justify-center mb-8">
              <Button
                variant="primary"
                className="flex items-center gap-2 py-3 px-6 h-auto text-base"
                onClick={handleSaveRootCA}
                disabled={port === 0}
              >
                <Download className="w-5 h-5" />
                Save Root CA Certificate
              </Button>
            </div>

            <div className="bg-slate-50 p-5 rounded-lg border border-slate-200">
              <h3 className="font-semibold text-slate-800 mb-3">Installation Steps (Windows)</h3>
              <ol className="list-decimal list-inside space-y-2 text-slate-700 text-sm">
                <li>
                  Open the saved{" "}
                  <code className="bg-slate-200 px-1 py-0.5 rounded text-xs">watchtower-root-ca.crt</code> file.
                </li>
                <li>
                  Click <strong>Install Certificate...</strong>
                </li>
                <li>
                  Select <strong>Local Machine</strong> (requires Admin) and click Next.
                </li>
                <li>
                  Select <strong>Place all certificates in the following store</strong> and click Browse...
                </li>
                <li>
                  Select <strong>Trusted Root Certification Authorities</strong> and click OK.
                </li>
                <li>Click Next and then Finish.</li>
                <li>
                  <strong>Restart your browser</strong> to apply changes.
                </li>
              </ol>
            </div>

            <div className="mt-6 pt-4 border-t border-slate-100">
              <P className="text-slate-500 text-xs">
                <strong>macOS Users:</strong> Double-click the .crt file → Add to Keychain (System) → Double-click the
                added certificate → Trust → Always Trust.
              </P>
            </div>
          </Card>

          {/* PAC */}
          <Card className="p-6">
            <H2 className="mb-2">Browser Proxy Configuration (PAC)</H2>
            <P className="text-slate-600 mb-3">
              Enter the URL below in your system or browser's automatic proxy configuration.
            </P>
            <div className="bg-slate-100 rounded-lg p-4 font-mono text-sm break-all">{pacUrl || "—"}</div>
            <P className="text-slate-500 text-sm mt-3">
              Windows: Settings → Network & Internet → Proxy → Use setup script
              <br />
              macOS: System Settings → Network → Advanced → Proxies → Automatic proxy configuration URL
            </P>
          </Card>

          {/* 수동 프록시 */}
          <Card className="p-6">
            <H2 className="mb-2">Manual proxy setup</H2>
            <P className="text-slate-600 mb-2">To use manual proxy instead of PAC:</P>
            <ul className="list-disc list-inside text-slate-600 space-y-1">
              <li>
                Address: <code className="bg-slate-100 px-1 rounded">127.0.0.1</code>
              </li>
              <li>
                Port: <code className="bg-slate-100 px-1 rounded">{port}</code>
              </li>
            </ul>
          </Card>
        </div>
      )}
    </div>
  );
}
