export const en = {
  title: "Settings",
  subtitle: "Global app settings. DNS server is used for proxy pass-through and domain status checks.",
  langTitle: "Display language",
  langDesc: "Choose the display language for the application interface.",
  langEn: "English",
  langKo: "한국어",
  updateTitle: "Software update",
  updateDesc: "Check for app updates. Updates are delivered via GitHub Releases.",
  updateChecking: "Checking...",
  updateCheckBtn: "Check for updates",
  updateClickToCheck: "Click to check for updates",
  dnsTitle: "DNS server",
  dnsDesc:
    "Used when resolving hostnames: proxy pass-through (when no route matches) and domain status checks. Leave empty to use system DNS. Example:",
  dnsLabel: "DNS server (IP or IP:port)",
  dnsPlaceholder: "8.8.8.8 or 1.1.1.1:53",
  dnsSave: "Save",
  dnsCurrent: "Current:",
  backupTitle: "Backup & restore",
  backupDesc:
    "Export all app data (domains, groups, proxy routes, DNS setting) to a JSON file, or import from a previously exported file. Import replaces current data.",
  backupExport: "Export settings",
  backupImport: "Import settings",
  alertExportSuccess: "Settings exported successfully.",
  alertExportFail: "Export failed. See console for details.",
  alertImportInvalid: "Invalid settings file format.",
  alertImportConfirm: "Import will replace all current domains, groups, proxy routes, and settings. Continue?",
  alertImportSuccess: "Settings imported. You may need to refresh domains and proxy pages.",
  alertImportFail: "Import failed. See console for details.",
} as const;
