export const en = {
  title: "API Schema",
  subtitle: "Explore OpenAPI schemas and test endpoints.",
  targetApi: "Target API",
  selectDomain: "-- Select a domain to inspect --",
  parsingSchema: "Parsing schema...",
  endpointsCount: (count: number) => `${count} eps`,
  noSchemaError: "No downloaded schema file found. Download it from the Dashboard first.",
  parseFailedError: (e: string) => `Schema parsing failed: ${e}`,
  searchEndpoints: "Search endpoints...",
  selectEndpoint: "Select an endpoint from the left.",
  endpointsInfo: (eps: number, tags: number) => `${eps} endpoints, ${tags} tag groups`,
  chooseDomainToStart: "Choose a domain above to explore the OpenAPI schema.",
  handoffEndpointMatched: (method: string, path: string) => `Matched OpenAPI endpoint: ${method.toUpperCase()} ${path}`,
  handoffEndpointNotFound: (method: string, path: string) =>
    `No matching OpenAPI endpoint for ${method.toUpperCase()} ${path}. Check schema download or search manually.`,
  requestHistoryToday: "Request History (Today)",
  noLogsFound: "No logs found for this endpoint today.",
  hasBody: "Has Body",
  noBody: "No Body",
  headersCount: (count: number) => `${count} Headers`,
  noHeaders: "No Headers",
  load: "Load",
  history: "History",
  send: "Send",
  parameters: "Parameters",
  body: "Body",
  customHeaders: "Custom Headers",
  origin: "Origin",
  pathname: "Pathname",
  addHeader: "Add Header",
  headerKey: "Header",
  headerValue: "Value",
  error: "Error",
  empty: "(empty)",
  headers: (count: number) => `Headers (${count})`,
  historyTitle: (method: string, path: string) => `History for ${method} ${path}`,
  registeredDomains: (count: number) => `${count} registered domains`,
  btnCopy: "Copy",
  copied: "Copied!",
  copiedDesc: "Copied to clipboard successfully.",
  copyHtml: "Copy HTML",
  copyMarkdown: "Copy Markdown",
  response: "Response",
  sending: "Sending...",
  responseStatus: "Status",
  responseTime: "Elapsed Time",
  responseBody: "Response Body",
  responseHeaders: "Response Headers",
  validateSchema: "Validate Response via JSON Schema",
  schemaText: "JSON Schema Definition",
  schemaPassed: "JSON Schema Validation Passed!",
  schemaFailed: "JSON Schema Validation Failed: ",
  openInClient: "Open in Client",
  fieldSettings: "Field Permissions",
  fieldMethod: "Method",
  tabEndpoints: "Endpoints",
  tabOptions: "Schema Options",
  optionsTitle: "API Schema Options",
  optionsSubtitle: "Choose which request fields can be edited when testing endpoints from the OpenAPI schema.",
  schemaUrlLabel: "OpenAPI Schema URL",
  schemaPlaceholder: "https://api.example.com/openapi.json",
  save: "Save",
  download: "Download",
  noSchemaDownloadAction: "Enter the OpenAPI schema URL below and click Download.",
  downloadSuccess: (size: string) => `Downloaded ${size} bytes successfully`,
  downloadFailed: (msg: string) => `Download failed: ${msg}`,
  schemaSaved: "Schema URL saved.",
  apiBodyLogging: "Record HTTP Bodies (Request/Response)",
  apiBodyLoggingDesc: "Save request and response bodies when logging API traffic. Requires API logging to be enabled.",
};
