import type { en } from "./en";

type TranslationSchema = {
  [K in keyof typeof en]: (typeof en)[K] extends (...args: infer A) => unknown ? (...args: A) => string : string;
};

export const ko: TranslationSchema = {
  title: "API 스키마",
  subtitle: "OpenAPI 스키마를 탐색하고 엔드포인트를 테스트합니다.",
  targetApi: "대상 API",
  selectDomain: "-- 조사할 도메인을 선택하세요 --",
  parsingSchema: "스키마 파싱 중...",
  endpointsCount: (count: number) => `${count}개 엔드포인트`,
  noSchemaError: "다운로드된 스키마 파일이 없습니다. Dashboard에서 먼저 다운로드하세요.",
  parseFailedError: (e: string) => `스키마 파싱 실패: ${e}`,
  searchEndpoints: "엔드포인트 검색...",
  selectEndpoint: "왼쪽에서 엔드포인트를 선택하세요.",
  endpointsInfo: (eps: number, tags: number) => `${eps}개 엔드포인트, ${tags}개 태그 그룹`,
  chooseDomainToStart: "위에서 도메인을 선택하면 OpenAPI 스키마를 탐색할 수 있습니다.",
  handoffEndpointMatched: (method: string, path: string) =>
    `OpenAPI 엔드포인트 매칭됨: ${method.toUpperCase()} ${path}`,
  handoffEndpointNotFound: (method: string, path: string) =>
    `${method.toUpperCase()} ${path}에 해당하는 OpenAPI 엔드포인트를 찾지 못했습니다. 스키마 다운로드 여부를 확인하거나 직접 검색하세요.`,
  requestHistoryToday: "요청 기록 (오늘)",
  noLogsFound: "오늘 이 엔드포인트에 대한 로그가 없습니다.",
  hasBody: "본문 있음",
  noBody: "본문 없음",
  headersCount: (count: number) => `${count}개 헤더`,
  noHeaders: "헤더 없음",
  load: "불러오기",
  history: "기록",
  send: "전송",
  parameters: "매개변수",
  body: "본문",
  customHeaders: "사용자 정의 헤더",
  origin: "Origin",
  pathname: "Pathname",
  addHeader: "헤더 추가",
  headerKey: "헤더",
  headerValue: "값",
  error: "오류",
  empty: "(비어 있음)",
  headers: (count: number) => `헤더 (${count})`,
  historyTitle: (method: string, path: string) => `${method} ${path} 기록`,
  registeredDomains: (count: number) => `${count}개 등록된 도메인`,
  btnCopy: "복사",
  copied: "복사 완료!",
  copiedDesc: "클립보드에 복사되었습니다.",
  copyHtml: "HTML 복사",
  copyMarkdown: "Markdown 복사",
  response: "응답",
  sending: "전송 중...",
  responseStatus: "상태 코드",
  responseTime: "소요 시간",
  responseBody: "응답 본문",
  responseHeaders: "응답 헤더",
  validateSchema: "응답 JSON Schema 검증",
  schemaText: "JSON Schema 정의",
  schemaPassed: "JSON Schema 검증 성공!",
  schemaFailed: "JSON Schema 검증 실패: ",
  openInClient: "클라이언트에서 열기",
  fieldSettings: "필드 편집 권한",
  fieldMethod: "메서드",
  tabEndpoints: "엔드포인트",
  tabOptions: "스키마 옵션",
  optionsTitle: "API 스키마 옵션",
  optionsSubtitle: "OpenAPI 스키마에서 엔드포인트를 테스트할 때 편집 가능한 요청 필드를 설정합니다.",
  schemaUrlLabel: "OpenAPI 스키마 URL",
  schemaPlaceholder: "https://api.example.com/openapi.json",
  save: "저장",
  download: "다운로드",
  noSchemaDownloadAction: "아래에서 OpenAPI 스키마 URL을 입력하고 다운로드하세요.",
  downloadSuccess: (size: string) => `${size} 바이트 다운로드 완료`,
  downloadFailed: (msg: string) => `다운로드 실패: ${msg}`,
  schemaSaved: "스키마 URL이 저장되었습니다.",
  apiBodyLogging: "요청/응답 본문(Body) 기록",
  apiBodyLoggingDesc: "API 트래픽 로깅 시 요청 및 응답 본문을 저장합니다. API 로깅이 활성화된 상태여야 합니다.",
};
