export const en = {
  title: "Monitoring Domains",
  subtitle: "Manage the status of all registered domains conveniently in one place.",
  btnGroups: "Groups",
  btnDomain: "Add Domain",
  searchPlaceholder: "Search domains...",
  filterAllGroups: "All Groups",
  filterNoGroup: "No Group",
  exportJson: "Export JSON",
  clearAll: "Clear All",
  total: "Total",
  noGroup: "No Group",
  confirmDelete: "Are you sure you want to delete this domain?",
  confirmDeleteTitle: "Delete Domain",
  confirmDeleteAction: "Delete",
  confirmClearAll: "🚨 Warning: All registered domains will be deleted. Do you want to proceed?",
  confirmClearAllTitle: "Clear All Confirmation",
  confirmClearAllAction: "Clear All Now",
  alertExportSuccess: "File saved successfully!",
  emptyTitle: "No domains registered",
  emptyDesc: "Check your search query or add a new domain.",

  listEmptySearchTitle: "No matching domains",
  listEmptySearchDesc: "No domains match your search query.",
  listEmptyClearSearch: "Clear Search",
  listEmptyNoDomainsTitle: "No domains registered",
  listEmptyNoDomainsDesc: "Click the button in the top right to register your first domain for monitoring.",
  listEmptyAddDomainBtn: "Add First Domain",

  editModalTitle: "Domain Settings",
  editModalDesc: "Change the address and group of this domain",
  editModalCancel: "Cancel",
  editModalUrlLabel: "URL",
  editModalGroupLabel: "Group",
  editModalSave: "Save Changes",
  editModalSaving: "Saving...",

  groupModalTitle: "Assign Group",
  groupModalDesc: (url: string) => `Select a group for ${url}`,
  groupModalNoGroup: "Deselect (No Group)",
  groupModalEmpty: "No groups registered yet. Please create one in the Group Management page first.",

  // Feature Badges
  featureMonitor: "Monitoring",
  featureProxy: "Proxy",
  featureApiLogging: "API Logging",
  featureOn: "ON",
  featureOff: "OFF",
  featureTogglingOn: "Toggling...",
  featureTogglingOff: "Toggling...",
  featureProxyGlobalOff: "Proxy is OFF. Start the proxy first.",
  featureProxyGlobalOffLink: "Go to Proxy",

  // Proxy Route mini-modal
  proxyRouteModalTitle: "Add Proxy Route",
  proxyRouteModalDesc: (domain: string) => `Configure local proxy route for ${domain}`,
  proxyRouteTargetHost: "Target Host",
  proxyRouteTargetPort: "Port",
  proxyRouteAdd: "Add Route",
  proxyRouteCancel: "Cancel",
  proxyRouteAdding: "Adding...",
};
