export const en = {
  title: "Monitor Settings",
  subtitle: "Select domains to check or ignore. You can batch update after selecting multiple items.",
  searchPlaceholder: "Search by URL or Group name...",
  checkedTitle: (count: number) => `Checked Domains (${count})`,
  uncheckedTitle: (count: number) => `Unchecked Domains (${count})`,
  selectAll: "Select All",
  deselect: "Deselect",
  checkedDesc: "Automatically monitored in the background.",
  uncheckedDesc: "Excluded from monitoring. Only checked during manual refresh.",
  noResults: (search: string) => (search ? "No results found." : "No domains registered."),
  allCheckedResult: "All domains are monitored.",
  disableBtn: (count: number) => `Selected Items → DO NOT Check (${count})`,
  enableBtn: (count: number) => `Selected Items → CHECK (${count})`,
  loading: "Loading...",
  defaultGroup: "Default",
} as const;
