/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatusIndexRouteImport } from './routes/status/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProxyIndexRouteImport } from './routes/proxy/index'
import { Route as DomainsIndexRouteImport } from './routes/domains/index'
import { Route as StatusSettingsRouteImport } from './routes/status/settings'
import { Route as StatusLogsRouteImport } from './routes/status/logs'
import { Route as ProxySetupRouteImport } from './routes/proxy/setup'
import { Route as ProxyDashboardRouteImport } from './routes/proxy/dashboard'
import { Route as DomainsDashboardRouteImport } from './routes/domains/dashboard'
import { Route as DomainsRegistIndexRouteImport } from './routes/domains/regist/index'
import { Route as DomainsGroupsIndexRouteImport } from './routes/domains/groups/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusIndexRoute = StatusIndexRouteImport.update({
  id: '/status/',
  path: '/status/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProxyIndexRoute = ProxyIndexRouteImport.update({
  id: '/proxy/',
  path: '/proxy/',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsIndexRoute = DomainsIndexRouteImport.update({
  id: '/domains/',
  path: '/domains/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusSettingsRoute = StatusSettingsRouteImport.update({
  id: '/status/settings',
  path: '/status/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusLogsRoute = StatusLogsRouteImport.update({
  id: '/status/logs',
  path: '/status/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProxySetupRoute = ProxySetupRouteImport.update({
  id: '/proxy/setup',
  path: '/proxy/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProxyDashboardRoute = ProxyDashboardRouteImport.update({
  id: '/proxy/dashboard',
  path: '/proxy/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsDashboardRoute = DomainsDashboardRouteImport.update({
  id: '/domains/dashboard',
  path: '/domains/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRegistIndexRoute = DomainsRegistIndexRouteImport.update({
  id: '/domains/regist/',
  path: '/domains/regist/',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsGroupsIndexRoute = DomainsGroupsIndexRouteImport.update({
  id: '/domains/groups/',
  path: '/domains/groups/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/domains/dashboard': typeof DomainsDashboardRoute
  '/proxy/dashboard': typeof ProxyDashboardRoute
  '/proxy/setup': typeof ProxySetupRoute
  '/status/logs': typeof StatusLogsRoute
  '/status/settings': typeof StatusSettingsRoute
  '/domains/': typeof DomainsIndexRoute
  '/proxy/': typeof ProxyIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/status/': typeof StatusIndexRoute
  '/domains/groups/': typeof DomainsGroupsIndexRoute
  '/domains/regist/': typeof DomainsRegistIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/domains/dashboard': typeof DomainsDashboardRoute
  '/proxy/dashboard': typeof ProxyDashboardRoute
  '/proxy/setup': typeof ProxySetupRoute
  '/status/logs': typeof StatusLogsRoute
  '/status/settings': typeof StatusSettingsRoute
  '/domains': typeof DomainsIndexRoute
  '/proxy': typeof ProxyIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/status': typeof StatusIndexRoute
  '/domains/groups': typeof DomainsGroupsIndexRoute
  '/domains/regist': typeof DomainsRegistIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/domains/dashboard': typeof DomainsDashboardRoute
  '/proxy/dashboard': typeof ProxyDashboardRoute
  '/proxy/setup': typeof ProxySetupRoute
  '/status/logs': typeof StatusLogsRoute
  '/status/settings': typeof StatusSettingsRoute
  '/domains/': typeof DomainsIndexRoute
  '/proxy/': typeof ProxyIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/status/': typeof StatusIndexRoute
  '/domains/groups/': typeof DomainsGroupsIndexRoute
  '/domains/regist/': typeof DomainsRegistIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/domains/dashboard'
    | '/proxy/dashboard'
    | '/proxy/setup'
    | '/status/logs'
    | '/status/settings'
    | '/domains/'
    | '/proxy/'
    | '/settings/'
    | '/status/'
    | '/domains/groups/'
    | '/domains/regist/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/domains/dashboard'
    | '/proxy/dashboard'
    | '/proxy/setup'
    | '/status/logs'
    | '/status/settings'
    | '/domains'
    | '/proxy'
    | '/settings'
    | '/status'
    | '/domains/groups'
    | '/domains/regist'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/domains/dashboard'
    | '/proxy/dashboard'
    | '/proxy/setup'
    | '/status/logs'
    | '/status/settings'
    | '/domains/'
    | '/proxy/'
    | '/settings/'
    | '/status/'
    | '/domains/groups/'
    | '/domains/regist/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DomainsDashboardRoute: typeof DomainsDashboardRoute
  ProxyDashboardRoute: typeof ProxyDashboardRoute
  ProxySetupRoute: typeof ProxySetupRoute
  StatusLogsRoute: typeof StatusLogsRoute
  StatusSettingsRoute: typeof StatusSettingsRoute
  DomainsIndexRoute: typeof DomainsIndexRoute
  ProxyIndexRoute: typeof ProxyIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  StatusIndexRoute: typeof StatusIndexRoute
  DomainsGroupsIndexRoute: typeof DomainsGroupsIndexRoute
  DomainsRegistIndexRoute: typeof DomainsRegistIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/': {
      id: '/status/'
      path: '/status'
      fullPath: '/status/'
      preLoaderRoute: typeof StatusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proxy/': {
      id: '/proxy/'
      path: '/proxy'
      fullPath: '/proxy/'
      preLoaderRoute: typeof ProxyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/': {
      id: '/domains/'
      path: '/domains'
      fullPath: '/domains/'
      preLoaderRoute: typeof DomainsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/settings': {
      id: '/status/settings'
      path: '/status/settings'
      fullPath: '/status/settings'
      preLoaderRoute: typeof StatusSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/logs': {
      id: '/status/logs'
      path: '/status/logs'
      fullPath: '/status/logs'
      preLoaderRoute: typeof StatusLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proxy/setup': {
      id: '/proxy/setup'
      path: '/proxy/setup'
      fullPath: '/proxy/setup'
      preLoaderRoute: typeof ProxySetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proxy/dashboard': {
      id: '/proxy/dashboard'
      path: '/proxy/dashboard'
      fullPath: '/proxy/dashboard'
      preLoaderRoute: typeof ProxyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/dashboard': {
      id: '/domains/dashboard'
      path: '/domains/dashboard'
      fullPath: '/domains/dashboard'
      preLoaderRoute: typeof DomainsDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/regist/': {
      id: '/domains/regist/'
      path: '/domains/regist'
      fullPath: '/domains/regist/'
      preLoaderRoute: typeof DomainsRegistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/groups/': {
      id: '/domains/groups/'
      path: '/domains/groups'
      fullPath: '/domains/groups/'
      preLoaderRoute: typeof DomainsGroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DomainsDashboardRoute: DomainsDashboardRoute,
  ProxyDashboardRoute: ProxyDashboardRoute,
  ProxySetupRoute: ProxySetupRoute,
  StatusLogsRoute: StatusLogsRoute,
  StatusSettingsRoute: StatusSettingsRoute,
  DomainsIndexRoute: DomainsIndexRoute,
  ProxyIndexRoute: ProxyIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StatusIndexRoute: StatusIndexRoute,
  DomainsGroupsIndexRoute: DomainsGroupsIndexRoute,
  DomainsRegistIndexRoute: DomainsRegistIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
