/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DomainsIndexRouteImport } from './routes/domains/index'
import { Route as DomainsStatusIndexRouteImport } from './routes/domains/status/index'
import { Route as DomainsRegistIndexRouteImport } from './routes/domains/regist/index'
import { Route as DomainsStatusLogsRouteImport } from './routes/domains/status/logs'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsIndexRoute = DomainsIndexRouteImport.update({
  id: '/domains/',
  path: '/domains/',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsStatusIndexRoute = DomainsStatusIndexRouteImport.update({
  id: '/domains/status/',
  path: '/domains/status/',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRegistIndexRoute = DomainsRegistIndexRouteImport.update({
  id: '/domains/regist/',
  path: '/domains/regist/',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsStatusLogsRoute = DomainsStatusLogsRouteImport.update({
  id: '/domains/status/logs',
  path: '/domains/status/logs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/domains/': typeof DomainsIndexRoute
  '/domains/status/logs': typeof DomainsStatusLogsRoute
  '/domains/regist/': typeof DomainsRegistIndexRoute
  '/domains/status/': typeof DomainsStatusIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/domains': typeof DomainsIndexRoute
  '/domains/status/logs': typeof DomainsStatusLogsRoute
  '/domains/regist': typeof DomainsRegistIndexRoute
  '/domains/status': typeof DomainsStatusIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/domains/': typeof DomainsIndexRoute
  '/domains/status/logs': typeof DomainsStatusLogsRoute
  '/domains/regist/': typeof DomainsRegistIndexRoute
  '/domains/status/': typeof DomainsStatusIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/domains/'
    | '/domains/status/logs'
    | '/domains/regist/'
    | '/domains/status/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/domains'
    | '/domains/status/logs'
    | '/domains/regist'
    | '/domains/status'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/domains/'
    | '/domains/status/logs'
    | '/domains/regist/'
    | '/domains/status/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DomainsIndexRoute: typeof DomainsIndexRoute
  DomainsStatusLogsRoute: typeof DomainsStatusLogsRoute
  DomainsRegistIndexRoute: typeof DomainsRegistIndexRoute
  DomainsStatusIndexRoute: typeof DomainsStatusIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/': {
      id: '/domains/'
      path: '/domains'
      fullPath: '/domains/'
      preLoaderRoute: typeof DomainsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/status/': {
      id: '/domains/status/'
      path: '/domains/status'
      fullPath: '/domains/status/'
      preLoaderRoute: typeof DomainsStatusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/regist/': {
      id: '/domains/regist/'
      path: '/domains/regist'
      fullPath: '/domains/regist/'
      preLoaderRoute: typeof DomainsRegistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/status/logs': {
      id: '/domains/status/logs'
      path: '/domains/status/logs'
      fullPath: '/domains/status/logs'
      preLoaderRoute: typeof DomainsStatusLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DomainsIndexRoute: DomainsIndexRoute,
  DomainsStatusLogsRoute: DomainsStatusLogsRoute,
  DomainsRegistIndexRoute: DomainsRegistIndexRoute,
  DomainsStatusIndexRoute: DomainsStatusIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
