export const en = {
  title: "Add New Targets",
  subtitle: "Enter one or more domains to start monitoring their health and uptime.",
  assignGroup: "Assign to Group",
  noGroupDefault: "No Group (Default)",
  groupTip: "Tip: You can manage groups in the Groups section of the sidebar.",
  importUrls: "Import URLs",
  placeholder: "example.com\napi.service.io, dev.test.com",
  uploadJson: "Upload JSON",
  export: "Export",
  parseBtn: "Parse & Add",
  startMonitor: "Start Monitoring",
  queue: "Queue",
  clear: "Clear",
  importAtRegist: "Group for registration",
  noDomainsInQueue: "No domains in queue",
  alertFileSaved: "File saved successfully!",
  alertInvalidJson: "Invalid JSON file format.",
  skippedMessage: (newOnes: number, skipped: number) => `${newOnes} added, ${skipped} already registered (skipped)`,
  importedMessage: (count: number) => `${count} URLs imported from file.`,
} as const;
