export const en = {
  home: "Home",
  domains: "Domains",
  monitor: "Monitoring",
  proxy: "Proxy",
  policy_group: "Guide Management",
  apis: "APIs",
  dashboard: "Dashboard",
  regist: "Regist",
  groups: "Groups",
  logs: "Logs",
  settings: "Settings",
  setup: "Setup",
  inspector: "Inspector & Settings",
  policy_list: "Guide List",
  live_capture: "Live Capture",
  apiSchema: "API Schema",
  jsonSchema: "JSON Schema",
  server_logs: "Server Logs",
  mocking: "Mocking",
  mobileConnect: "Mobile Connect",
  apiClient: "API Client",
  sandbox: "Sandbox",
  sandboxPipeline: "Data Pipeline",
  sandboxCrypto: "Crypto Tool",
  sandboxPreview: "UI Preview",
} as const;
