export const en = {
  title: "API Schema",
  subtitle: "Explore OpenAPI schemas and test endpoints.",
  targetApi: "Target API",
  selectDomain: "-- Select a domain to inspect --",
  parsingSchema: "Parsing schema...",
  endpointsCount: (count: number) => `${count} eps`,
  noSchemaError: "No downloaded schema file found. Download it from the Dashboard first.",
  parseFailedError: (e: string) => `Schema parsing failed: ${e}`,
  searchEndpoints: "Search endpoints...",
  selectEndpoint: "Select an endpoint from the left.",
  endpointsInfo: (eps: number, tags: number) => `${eps} endpoints, ${tags} tag groups`,
  chooseDomainToStart: "Choose a domain above to explore the OpenAPI schema.",
  requestHistoryToday: "Request History (Today)",
  noLogsFound: "No logs found for this endpoint today.",
  hasBody: "Has Body",
  noBody: "No Body",
  headersCount: (count: number) => `${count} Headers`,
  noHeaders: "No Headers",
  load: "Load",
  history: "History",
  send: "Send",
  parameters: "Parameters",
  body: "Body",
  customHeaders: "Custom Headers",
  error: "Error",
  empty: "(empty)",
  headers: (count: number) => `Headers (${count})`,
  historyTitle: (method: string, path: string) => `History for ${method} ${path}`,
  registeredDomains: (count: number) => `${count} registered domains`,
};
